Added user stories map ref
pabdulin/howto-clinic pull request #1
Opened 2021-08-03 07:28 UTC by pabdulin

2021-08-03 13:10 UTC, elukianov requested changes

2021-08-03 13:10 UTC, elukianov commented on README.md
> +[User Stories Map on miro.com](https://miro.com/app/board/o9J_l4Nx82Q=/)
Нет доступа, не хочет ничего показывать(

2021-08-03 17:10 UTC, pabdulin commented on README.md
> +[User Stories Map on miro.com](https://miro.com/app/board/o9J_l4Nx82Q=/)
Поправил публичный доступ, должно работать теперь.

2021-08-04 12:07 UTC, elukianov commented on README.md
> +[User Stories Map on miro.com](https://miro.com/app/board/o9J_l4Nx82Q=/)
- Опционально: Предоставить номер врачебной лицензии - этот шаг теоретически можно соединить с приемом врача на работу. Указываем данные и сразу номер. Но это зависит от процесса, поэтому оставим так

- Диагноз в карточке - нет действия. Человеку в контексте понятно что тут должно происходить, а не в контексте - уже не очень. Нужно немного переформулировать "Выставить диагноз" или же "Зафиксировать диагноз в карточке". У нас учебный пример, в реальной жизни нужно слушать как говорят эксперты

- Направить на анализы - у нас в задании нет прямого направления на анализы, есть направить на дополнительное обследование

- Уведомить о предстоящем приеме, автоматически назначить... - лучше сформулировать от лица пациента

- Предоставить доступ к функционалу нейросети - это смахивает на какую-то техническую штуку, потому как непонятно какое конечно действие должно быть совершено. Лучше сформулировать как Выполнить исследование при помощи нейросети

- Получить и сохранить данные - слово сохранить выглядит как какая-то техническая подробность.

- Нет закрытия заявки

- Нет передачи диагноза в поликлиннику

2021-08-04 12:09 UTC, elukianov requested changes
Комментарии в дискусии

2021-08-07 15:28 UTC, pabdulin commented on README.md
> +[User Stories Map on miro.com](https://miro.com/app/board/o9J_l4Nx82Q=/)
Спасибо, поправил, проверь пожалуйста.

2021-08-16 07:35 UTC, merged